### ISSUE TITLE
Curate tweepy request to fetch 100 most recent Tweets

### ISSUE THREAD

**Issue by csuttner** [skutchiewutch/bizzle#18]
Currently, the tweepy module fetches 3000+ tweets.

We should limit this for local testing purposes so we don't get close to breaching the 500,000 monthly allowance.

**Comment by evfairchild** [comment]
this is done, but I need to add the batch query logic from master/develop back into the 'issue-022-ef-mtrewrite' branch.  This will be rolled into a separate issue.
