### ISSUE TITLE
Begin Word Processing Module 

### ISSUE THREAD

**Issue by evfairchild** [skutchiewutch/bizzle#21]
all below methods accept list of tweets as inputs.  ["this is a tweet", "test woo foo"]
add Tweet Count method -> int
add individual word count method -> dict
add Distinct Word method -> int

**Comment by evfairchild** [comment]
I intend to break this module out when we use more advanced data analysis.  For now, this issue should be merged with the Issue #22.    We will create a separate issue when we are ready to adopt more advanced data processing methods.

**Comment by csuttner** [comment]
Thanks for clarifying your approach - I think we'll have a lot of refactoring to do as we refine our project after reaching a certain level of features.

**Comment by evfairchild** [comment]
All in one approach selected for now.  Will open separate issue for new word processing module at later sprint cycle.
