### ISSUE TITLE
Begin Twitter Module

### ISSUE THREAD

**Issue by evfairchild** [skutchiewutch/bizzle#22]
Twitter GET requests (limit 100 for now) -> json.load -> dict

Dict processing method: strip out tweet text only.  Outputs into list

Calls on Word Processing module and build output dict

json.dump output dict to final json format (to be agreed upon)

**Comment by evfairchild** [comment]
renamed to Twitter module, so we do not to get confused with the existing meantweets directory containing frontend application code.  The Twitter module is used for Twitter data requests and low-level data aggregation.

**Comment by csuttner** [comment]
The naming convention makes sense

**Comment by csuttner** [comment]
Would we prefer to strip stopwords using nltk? https://pythonspot.com/nltk-stop-words/
